string J1_NEGATIVE = "j1-"
string J1_POSITIVE = "j1+"

string J2_NEGATIVE = "j2-"
string J2_POSITIVE = "j2+"

string J3_NEGATIVE = "j3-"
string J3_POSITIVE = "j3+"

string J4_NEGATIVE = "j4-"
string J4_POSITIVE = "j4+"

string X_NEGATIVE = "X-"
string X_POSITIVE = "X+"

string Y_NEGATIVE = "Y-"
string Y_POSITIVE = "Y+"

string Z_NEGATIVE = "Z-"
string Z_POSITIVE = "Z+"

string RX_NEGATIVE = "Rx-"
string RX_POSITIVE = "Rx+"

string RY_NEGATIVE = "Ry-"
string RY_POSITIVE = "Ry+"

string RZ_NEGATIVE = "Rz-"
string RZ_POSITIVE = "Rz+"

string STOP = ""

string jog_mode