name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: |
      ((github.event.action == 'labeled') &&
        (github.event.label.name == 'TESTING')) ||
      ((github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'TESTING')) ||
      (github.ref == 'refs/heads/main')
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ros_distribution: [galactic]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: |
            mg400_bringup
            mg400_interface
            mg400_description
            mg400_msgs
            mg400_node
            mg400_joy
          vcs-repo-file-url: mg400.repos
