name: ci_humble

on:
  push:
    branches:
      - "humble"
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: |
      ((github.event.action == 'labeled') && (github.event.label.name == 'TESTING') && (github.base_ref == 'humble' )) ||
      ((github.event.action == 'synchronize') && (github.base_ref == 'humble') && contains(github.event.pull_request.labels.*.name, 'TESTING')) ||
      (github.ref_name == 'humble')
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ros_distribution: [humble]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: |
            mg400
            mg400_bringup
            mg400_description
            mg400_interface
            mg400_joy
            mg400_msgs
            mg400_node
            mg400_plugin
            mg400_plugin_base
          vcs-repo-file-url: build_depends.repos
